name: 'Craft CMS - Atomic Deploy Action'
description: 'Atomically deploy your Craft projects.'
inputs:
  host:
    description: 'Server IP'
    required: true
  port:
    description: 'Server Port'
    required: false
    default: 22
  user:
    description: 'Server User'
    required: true
  ssh_key:
    description: 'Private SSH key'
    required: true
  local_path:
    description: 'Path to your built artifacts'
    default: ${{ GITHUB_WORKSPACE }}
    required: false
  remote_path:
    description: 'Absolute remote path'
    required: true
  remote_cache_dir:
    description: 'Relative path to source files'
    default: deploy-cache
    required: false
  post_deploy:
    description: 'Post deploy scripts'
    required: false
  rsync:
    description: 'Whether to rsync the files, uses local_path for the source'
    default: true
  rsync_ignore_file:
    description: 'A text file listing files to ignore during rsync'
    default: rsync-ignore.txt
outputs:
  webroot:
    description: 'The new webroot'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.host }}
    - ${{ inputs.port }}
    - ${{ inputs.user }}
    - ${{ inputs.ssh_key }}
    - ${{ inputs.local_path }}
    - ${{ inputs.remote_path }}
    - ${{ inputs.remote_cache_dir }}
    - ${{ inputs.post_deploy }}
    - ${{ inputs.rsync }}
    - ${{ inputs.rsync_ignore_file }}
branding:
  icon: 'upload-cloud'
  color: 'red'